from __future__ import annotations

DEFAULT_CHANNEL_MAP: dict[str, dict[str, object]] = {
    "rpm": {"field": "rpm"},
    "engine": {"field": "rpm"},
    "enginespeed": {"field": "rpm"},
    "speed": {"field": "speedKph"},
    "vss": {"field": "speedKph"},
    "vehicleSpeed": {"field": "speedKph"},
    "speedmph": {"field": "speedKph", "transform": "mph_to_kph"},
    "gear": {"field": "gear", "transform": "gear"},
    "reverse": {"field": "reverse", "transform": "bool"},
    "clt": {"field": "coolantC"},
    "coolant": {"field": "coolantC"},
    "coolantc": {"field": "coolantC"},
    "coolantf": {"field": "coolantC", "transform": "f_to_c"},
    "oiltemp": {"field": "oilC"},
    "oiltempc": {"field": "oilC"},
    "oiltempf": {"field": "oilC", "transform": "f_to_c"},
    "transmissiontemp": {"field": "transmissionC"},
    "transmissiontempc": {"field": "transmissionC"},
    "iat": {"field": "iatC"},
    "mat": {"field": "iatC"},
    "airtemp": {"field": "iatC"},
    "ambient": {"field": "ambientC"},
    "ambientc": {"field": "ambientC"},
    "batt": {"field": "batteryV"},
    "battery": {"field": "batteryV"},
    "batteryv": {"field": "batteryV"},
    "fuel": {"field": "fuelPct"},
    "fuellevel": {"field": "fuelPct"},
    "fuelpct": {"field": "fuelPct"},
    "range": {"field": "rangeKm"},
    "rangekm": {"field": "rangeKm"},
    "fuelrate": {"field": "fuelRateLph"},
    "fuelratelph": {"field": "fuelRateLph"},
    "map": {"field": "mapKpa"},
    "mapkpa": {"field": "mapKpa"},
    "mappsi": {"field": "mapKpa", "transform": "psi_to_kpa"},
    "baro": {"field": "baroKpa"},
    "barokpa": {"field": "baroKpa"},
    "boost": {"field": "boostKpa"},
    "boostkpa": {"field": "boostKpa"},
    "boostpsi": {"field": "boostKpa", "transform": "psi_to_kpa"},
    "lambda": {"field": "lambda"},
    "afr": {"field": "afr"},
    "odometer": {"field": "odometerKm"},
    "odometerkm": {"field": "odometerKm"},
    "trip": {"field": "odometerTripKm"},
    "tripkm": {"field": "odometerTripKm"},
    "ambientlux": {"field": "ambientLux"},
    "nightmode": {"field": "nightMode", "transform": "bool"},
    "gpslat": {"field": "gps.lat"},
    "latitude": {"field": "gps.lat"},
    "gpslng": {"field": "gps.lng"},
    "gpslon": {"field": "gps.lng"},
    "longitude": {"field": "gps.lng"},
    "gpsalt": {"field": "gps.alt"},
    "gpsheading": {"field": "gps.heading"},
    "gpsspeed": {"field": "gps.speedMs"},
    "gpsspeedms": {"field": "gps.speedMs"},
    "gpsspeedkph": {"field": "gps.speedMs", "transform": "kph_to_ms"},
    "gpsaccuracy": {"field": "gps.accuracyM"},
    "gpssatellites": {"field": "gps.satellites"},
}

